hhffff

diff --git a/app/client/Dockerfile.client.staging b/app/client/Dockerfile.client.staging
--- a/app/client/Dockerfile.client.staging
+++ b/app/client/Dockerfile.client.staging
@@ -1,26 +1,31 @@
-FROM node:alpine3.18 as build
+# Stage 1: Build the React App
+FROM node:alpine3.18 AS builder
 
 WORKDIR /app/client
 
-COPY package*.json .
-
+COPY package*.json ./
 
 # Install dependencies
 RUN npm install
 
-COPY . .
+COPY . ./
 
 # Build the React app
-RUN npm run build
+#RUN npm run build || (echo "Build failed" && exit 1)
 
-## Final Image
-FROM nginx
+# Debugging: Check build output
+#RUN ls -al /app/client/build
+
+## Stage 2: Serve with Nginx
+FROM nginx:latest
 
 WORKDIR /usr/share/nginx/html
 RUN rm -rf *
 
-# Copy React build to Nginx
-COPY --from=builder /app/client/build /usr/share/nginx/html
+# Copy the build files from the 'builder' stage
+#COPY --from=builder /app/client/build /usr/share/nginx/html
+COPY ./dist /usr/share/nginx/html
+
 
 COPY nginx.conf /etc/nginx/nginx.conf
 
@@ -31,3 +36,4 @@ RUN chown -R nginx:nginx /usr/share/nginx/html
 EXPOSE 80
 
 CMD ["nginx", "-g", "daemon off;"]
+
